version: 2

aliases:
  # build environment
  - &docker-linux
    docker:
      - image: centos:7
    working_directory: /root/src

  # system dependencies
  - &install-system-deps
    run:
      name: Install system dependencies
      command: scripts/install-system-deps.sh
  - &install-stack
    run:
      name: Install stack
      command: |
        curl -sSL https://get.haskellstack.org/ | sh
        stack --version

  # cache
  - &build-cache-key
    run:
      name: Build cache key
      command: |
        FILES=(
          stack.yaml
          self-extract.cabal
        )
        cat "${FILES[@]}" > cache-key.txt
  - &cache-key
    v2-{{ checksum "cache-key.txt" }}
  - &install-stack-deps
    run:
      name: Build external dependencies
      command: stack build --only-dependencies

  # build steps
  - &run-build
    run:
      name: Build package
      command: |
        stack build self-extract
        # build the basic example to test self-extraction without build environment
        example/basic/build.sh

  # test steps
  - &run-basic-example
    run:
      name: Run the basic example
      command: |
        example/basic/build/run-example dest/
        [ -f dest/hello-world.txt ]
  - &run-cabal-example
    run:
      name: Run the cabal example
      command: |
        stack build self-extract-cabal
        stack exec self-extract-cabal <<< dest/
        [ -f dest/hello-world.txt ]

jobs:
  prebuild:
    <<: *docker-linux
    steps:
      - checkout
      - *build-cache-key
      - persist_to_workspace:
          root: .
          paths:
            - cache-key.txt

  build:
    <<: *docker-linux
    steps:
      - checkout
      - attach_workspace:
          at: .
      - *install-system-deps
      - *install-stack
      - restore_cache:
          key: *cache-key
      - *install-stack-deps
      - save_cache:
          key: *cache-key
          paths:
            - ~/.stack
      - *run-build
      - persist_to_workspace:
          root: .
          paths:
              - .stack-work
              - example/basic/build/

  basic-example:
    <<: *docker-linux
    steps:
      - checkout
      - attach_workspace:
          at: .
      - *run-basic-example

  cabal-example:
    <<: *docker-linux
    steps:
      - checkout
      - attach_workspace:
          at: .
      - *install-system-deps
      - *install-stack
      - restore_cache:
          key: *cache-key
      - *run-cabal-example

workflows:
  version: 2

  build_and_test:
    jobs:
      - prebuild
      - build:
          requires:
            - prebuild
      - basic-example:
          requires:
            - build
      - cabal-example:
          requires:
            - build
